# Generated by Django 5.0.6 on 2024-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_transaction_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Purchase'), (3, 'Return')], null=True),
        ),
    ]
