# Generated by Django 5.0.6 on 2024-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_transaction_is_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Purchase'), (3, 'Returned Successfull')], null=True),
        ),
    ]
