# Generated by Django 5.0.6 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Book/templates/media/uploads/'),
        ),
    ]
