# Generated by Django 5.0.6 on 2024-08-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_rename_book_order_book_alter_bookmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='publication_company',
            new_name='category',
        ),
    ]
