# Generated by Django 5.0.6 on 2024-08-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_rename_publication_company_bookmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='category',
            new_name='category_name',
        ),
    ]
