# Generated by Django 5.0.6 on 2024-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_rename_category_bookmodel_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
