# Generated by Django 5.0.6 on 2024-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_bookmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
