# Generated by Django 5.0.6 on 2024-08-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_alter_bookmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
